theNorstroem/FuroBaseComponents

packages/furo-form/fd-input-row.js
packages/furo-form/furo-collapsible-box.js
packages/furo-input/FuroInputBase.js
packages/furo-input/furo-button.js

Extended styling possibilities

---

packages/framework/furo.js
packages/framework/iconset.js
packages/furo-layout/furo-icon.js

furo-icon: visual component for display svg icon
Iconset: for managing iconset

feat: add furo-icon

---

packages/furo-input/furo-reference-search.js
packages/furo-route/coverage/lcov-report/furo-location.js.html

fix: fix e.path

---

packages/furo-data-input/demo/demo-furo-data-checkbox-input.js
packages/furo-input/demo/demo-furo-checkbox-input.js
packages/furo-input/furo-checkbox-input.js
packages/furo-input/furo-checkbox.js

remove filled , modify styling for condensed

chore: refactoring furo-checkbox-input

---

_page/api/demoimports.js
_page/api/nav_config.js
packages/furo-notification/README.md
packages/furo-notification/analysis.json
packages/furo-notification/demo/demo-furo-snackbar-display.js
packages/furo-notification/demo/demos.js
packages/furo-notification/demo/loading-indicator.html
packages/furo-notification/demo/produce-snackbar-data.js
packages/furo-notification/furo-catalog.js
packages/furo-notification/furo-snackbar-display.js
packages/furo-notification/furo-snackbar.js
packages/furo-notification/package.json
packages/furo-notification/polymer.json
packages/furo-notification/test/index.html

Furo snackbar

---

packages/furo-route/src/furo-location.js
packages/furo-route/test/furo-location.test.js

use litElement in furo-location

Fix furo location

---

mockdata/experiments/1/get.json
packages/furo-data-input/test/furo-data-money-input.test.js

modify mock data for entity agent tests.

fix: modify mock data for entity agent tests.

---

packages/furo-specs/_scripts/templates/make/ServiceFromType.tmpl

remove proto type in query for type spec im ServiceFromType.tmpl

feat: remove proto type in query for type spec im ServiceFromType.tmpl

---

packages/furo-data/src/furo-collection-agent.js

give a hint when by requesting with the query param which is not defined in the spec.

give a hint when by requesting with the query param which is not defined in the spec.

---

packages/furo-data/src/furo-data-object.js
packages/furo-data/src/furo-entity-agent.js
packages/furo-data/src/lib/RepeaterNode.js
packages/furo-data/test/furo-entity-agent-fieldmask.test.js

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/field_mask.proto

fix: update_mask according to field_mask.proto

---

packages/furo-data/src/lib/UniversalFieldNodeBinder.js

asignment moved to if checked part

fix: fieldoptions.list are not always available

---

packages/furo-data/demos/demo-furo-sortby-container.js
packages/furo-data/src/lib/FieldNode.js
packages/furo-data/src/lib/UniversalFieldNodeBinder.js
packages/furo-data/test/furo-sortby-container.test.js
packages/furo-ui5/src/furo-ui5-data-collection-dropdown.js
packages/furo-ui5/src/furo-ui5-data-number-input.js
packages/furo-ui5/src/furo-ui5-data-password-input.js
packages/furo-ui5/src/furo-ui5-data-reference-search.js
packages/furo-ui5/test/furo-ui5-data-collection-dropdown.test.js

add item-selected event to furo-data-ui5-reference-search

feat: add item-selected event to furo-data-ui5-reference-search

---

packages/furo-data/test/furo-data-object.test.js
packages/furo-ui5/test/furo-ui5-data-collection-dropdown.test.js
packages/furo-ui5/test/furo-ui5-data-date-picker.test.js

fix: fix tests

---

packages/furo-data-input/src/furo-data-sign-pad.js
packages/furo-data/src/lib/DataObject.js

clear errors without any pre condition like pristine

Minor fixes

---

packages/furo-ui-builder/_scripts/init-with-hook.js
packages/furo-ui-builder/furo.ui.spec.conf.json
packages/furo-ui-builder/sample.furo.ui.spec.conf.json

new config attribute:
"specFormat": "yaml"
support for json or yaml spec files

fix: configurable yaml support

---

packages/furo-data-input/src/furo-data-date-input.js
packages/furo-data-input/src/furo-data-property-display.js
packages/furo-data-input/src/furo-data-property.js
packages/furo-data-input/src/furo-data-sign-pad.js
packages/furo-data/src/lib/FieldNode.js
packages/furo-fbp/src/flow-repeat.js
packages/furo-framework/src/system.js
packages/furo-notification/src/furo-banner.js
packages/furo-ui-builder/_scripts/u33eBuilder.js
packages/furo-ui5/src/furo-ui5-data-checkbox-input-labeled.js
packages/furo-ui5/src/furo-ui5-data-collection-dropdown-labeled.js
packages/furo-ui5/src/furo-ui5-data-date-picker-labeled.js
packages/furo-ui5/src/furo-ui5-data-date-picker.js
packages/furo-ui5/src/furo-ui5-data-money-input-labeled.js
packages/furo-ui5/src/furo-ui5-data-number-input-labeled.js
packages/furo-ui5/src/furo-ui5-data-password-input-labeled.js
packages/furo-ui5/src/furo-ui5-data-reference-search-labeled.js
packages/furo-ui5/src/furo-ui5-data-ro-labeled.js
packages/furo-ui5/src/furo-ui5-data-text-input-labeled.js
packages/furo-ui5/src/furo-ui5-data-textarea-input-labeled.js
packages/furo-ui5/src/furo-ui5-notification.js
packages/furo-ui5/src/lib/Ui5PropertyStandardMapping.js

feat: support furo.type.Date

---

packages/furo-framework/src/system.js
packages/furo-navigation/src/furo-tree.js
packages/furo-ui5/src/furo-ui5-data-collection-dropdown.js
packages/furo-ui5/src/furo-ui5-data-input.js

fix: trivial fixes

---

packages/furo-data-input/demos/demo-furo-data-reference-search.js
packages/furo-data-input/src/furo-data-repeat.js
packages/furo-data/src/furo-collection-agent.js
packages/furo-data/src/lib/ValidatorNumericTypes.js
packages/furo-fbp/src/flow-repeat.js
packages/furo-input/src/lib/helper.js
packages/furo-input/test/furo-range-input.test.js
packages/furo-input/test/furo-select-input.test.js

focus-on-create focuses the newly created element. This feature was written in some examples, but never implemented !?

feat: furo-data-repeat.js focus-on-create 

---

packages/furo-data-input/demos/demo-furo-data-collection-dropdown.js
packages/furo-data-input/demos/demo-furo-data-collection-reference-dropdown.js
packages/furo-data-input/src/furo-data-collection-dropdown.js
packages/furo-framework/src/system.js
packages/furo-input/src/furo-select-input.js
packages/furo-ui5/src/furo-ui5-data-collection-dropdown.js
packages/furo-ui5/src/furo-ui5-data-display.js

furo-data-collection-dropdown should update bounded data

fix: furo-data-collection-dropdown should update bounded data

---

packages/furo-ui5/src/furo-ui5-data-checkbox-input.js

solve the not clickable problem in ui5-data-checkbox-input

fix: update slots in ui5-data-checkbox-input when value changed

---

packages/furo-ui-builder/_scripts/hook-init-repeat-ui5.js
packages/furo-ui5/demos/demo-furo-ui5-data-reference-search.js
packages/furo-ui5/src/furo-catalog.js
packages/furo-ui5/src/furo-ui5-data-repeat.js
packages/furo-ui5/src/lib/ui5-data-repeat-delete.js

The existing semi finished repeater component is based on FURO material components. This pull request adds ui5-icon component as delete element and some minor layout changes.

feat: semi-finished repeater tmpl according to SAP Fiori

---

packages/furo-ui5/src/furo-ui5-pagination-bar.js

--furo-ui5-pagination-bar-padding-right => fallback to spacing => fallback to 24px

feat: configurable right padding for pagination bar with style var

---

packages/furo-ui5/src/furo-ui5-data-display.js
packages/furo-ui5/src/furo-ui5-pagination-bar.js

Keyboard navigation for ui5 pagination bar

Minor ui5 improvements

---

packages/furo-ui5/src/furo-ui5-data-textarea-input.js

fix: update ui5-data-textarea-input by data-initiate and value-change.

---

packages/furo-form/src/furo-button-bar.js

make furo-button-bar exportable

feat: make furo-button-bar exportable

---

packages/furo-ui5/src/furo-ui5-card.js
packages/furo-ui5/src/furo-ui5-data-checkbox-input-labeled.js
packages/furo-ui5/src/furo-ui5-data-collection-dropdown-labeled.js
packages/furo-ui5/src/furo-ui5-data-date-time-display-labeled.js
packages/furo-ui5/src/furo-ui5-data-table.js
packages/furo-ui5/src/furo-ui5-form-field-container.js

feat: add css theme supports.

---

packages/furo-ui5/src/furo-ui5-data-input.js
packages/furo-ui5/src/lib/localeData.js

- valueStateMessage should not be initiated
- fix ui5 input error when valueStateMessage is not initiated

fix: valueStateMessage in data-ui5-input should not be initiated.

---

packages/furo-ui5/src/furo-ui5-header-panel.js

adjust styling for collapser in ui5-header-panel.

chore: adjust styling for collapser in ui5-header-panel.

---

packages/furo-data-input/src/furo-data-sign-pad.js

fix: clear data on clearing furo-data-sign-pad

---

package-lock.json
packages/furo-ui5/package.json
packages/furo-ui5/src/furo-ui5-data-checkbox-input.js
packages/furo-ui5/src/furo-ui5-data-radio-button-group.js
packages/furo-ui5/test/furo-ui5-data-collection-dropdown.test.js

feat: update ui5 to rc14.

---

packages/furo-data/src/lib/FieldNodeAdapter.js
packages/furo-ui5/src/furo-ui5-data-multi-input.js

chore: furo-ui5-data-multi-input.

---

packages/furo-navigation/demos/demo-furo-tree-qp.js
packages/furo-navigation/src/furo-tree.js

fix: tree and demo

---

packages/furo-route/src/furo-app-flow-router.js

Feature removed because windows and macos handles it differently.
todo: find a solution which works on every browser

fix: remove meta key handling
